### ISSUE TITLE
IntegerField doesn't allow default value of zero

### ISSUE THREAD

**Issue by outinspace** [potassco/clorm#23]
`rank = IntegerField(default=0)`
Produces the following error when I don't provide a value when creating my fact base:
`ValueError: Unspecified field rank has no default value`

`rank = IntegerField(default=1)`
Doesn't produce any errors.

Is this expected behavior?

**Comment by daveraja** [comment]
Thanks for picking up on this. 

It is a bug. It was checking for `not default` rather than `default is not None`.

I'll fix it and make a bug release (and push the updated anaconda package).

**Comment by outinspace** [comment]
Thanks for the quick response. Otherwise, I'm really enjoying using this library. I'm using it to write python unit tests around my logic program.

**Comment by daveraja** [comment]
Glad to hear that you are finding it useful. I find debugging logic programs tricky and error prone so am interested to see how Clorm can be extended to better support this. 

Anyway, this bug should now be fixed and new version has been pushed to anaconda:

``conda update -c potassco clorm``
