### ISSUE TITLE
feedback on the quick-start

### ISSUE THREAD

**Issue by bdelepine** [potassco/clorm#35]
Hi,

Few feedbacks on the quick-start https://github.com/potassco/clorm/blob/master/docs/clorm/quickstart.rst : 

Typo, "Assig**n**ment":
```
ctrl = Control(unifier=[Driver,Item,Assignment])
ctrl.load("quickstart.lp")
```

Import was missing:
```
from clorm import FactBase

drivers = [ Driver(name=n) for n in ["dave", "morri", "michael" ] ]
items = [ Item(name="item{}".format(i)) for i in range(1,6) ]
instance = FactBase(drivers + items)
```

Python somehow complained about the `nonlocal` keyword; it worked fine with `global`:
```
def on_model(model):
    global solution
    solution = model.facts(atoms=True)

ctrl.solve(on_model=on_model)
if not solution:
    raise ValueError("No solution found")
```

The quick-start was quite understandable otherwise. One more suggestion: maybe only import the placeholder "ph1_" when it is used, I was a bit puzzled by it at the beginning.

HTH

**Comment by daveraja** [comment]
Hi @bdelepine,

Thanks for the feedback and picking up the errors. I've updated as you suggested.

Regarding the ``nonlocal`` vs ``global`` keyword. It is a quirk of Python that you cannot refer to a variable at the global scope using the nonlocal keyword. The quickstart code in the example sub-directory (https://github.com/potassco/clorm/tree/master/examples/quickstart) wraps everything within a main() function. But this was not clear from the quickstart documentation, so I've replaced it with global in the documentation but added a comment about using nonlocal depending on the scope.

Regards, Dave.
