### ISSUE TITLE
clorm 1.1.0 release is broken

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clorm#40]
I am currently adding potassco packages to conda-forge. I wanted to add a clorm package too but installation failed because setup.py does not list all modules to be installed. Now I could add a patch but maybe it is better to fix this issue in a bugfix release to keep the recipe clean. I see you already addressed the issue in git.

Also, since we have pip packages now, clorm should list `clingo` as a dependency. See for example [here][dep].

[dep]: https://github.com/potassco/python-clingox/blob/37414994d8f5728be07541e97d905ef0f057fc07/setup.py#L16

Here is the current state (which fails to build because of the setup.py):
- https://github.com/rkaminsk/staged-recipes/blob/potassco-packages/recipes/clorm/meta.yaml

Feedback is welcome.

PS: I would like to add you as a maintainer to the clorm conda-forge package too. If you accept, you would have to add agree in a comment once I open a PR to add the package. Maintaining the package as such is very easy. Especially, since clorm is a pure python package.

**Comment by daveraja** [comment]
Thanks for trying this out. I will get onto fixing the setup.py.

Currently, clorm 1.1.0 doesn't work with clingo 5.5. The dev version (in the potassco dev conda channel) does work. I was originally aiming for a v2.0 release because I wanted to make a few changes that could break the original API. But this is taking a bit longer than I'd like so I think I will instead create a v1.2 release which will work with clingo 5.5.

I'm happy to be a maintainer of the clorm conda-forge package.

**Comment by rkaminsk** [comment]
Thanks. I think that having a release for the latest clingo version would be nice. Otherwise, clorm users are stuck with the old clingo version.

**Comment by daveraja** [comment]
@rkaminsk I think I've fixed the setup.py and am ready to create a 1.2.0 release. To test it I created a clean conda environment. Then from the `clorm` home directory I ran:

    $ pip install -e .

This downloaded clingo and I could then run the unit tests. Is there something else (or something better) I should do to test this?

BTW. When I ran the pip install it installed the clingo python module but not the clingo executable. Is this the expected behaviour? Here was the install output:

    $ pip install -e .
    Obtaining file://<path-to-clorm>/clorm

    Collecting clingo
      Downloading clingo-5.5.0.post3-cp38-cp38-manylinux2014_x86_64.whl (2.2 MB)
         |████████████████████████████████| 2.2 MB 5.4 MB/s 
    Collecting cffi
      Downloading cffi-1.14.5-cp38-cp38-manylinux1_x86_64.whl (411 kB)
         |████████████████████████████████| 411 kB 7.8 MB/s 
    Collecting pycparser
      Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |    ████████████████████████████████| 112 kB 10.1 MB/s 
     Installing collected packages: pycparser, cffi, clingo, Clorm
      Running setup.py develop for Clorm
    Successfully installed Clorm-1.2.0 cffi-1.14.5 clingo-5.5.0.post3 pycparser-2.20

Then trying to run clingo resulted in:

    $ clingo

    Command 'clingo' not found, but can be installed with:

    sudo apt install gringo

**Comment by rkaminsk** [comment]
The pip package does not install the clingo executable, just the python package. But you can still run "something like" clingo using

    python -m clingo

You could still run

    pip check

to see if all dependencies of clorm are installed properly.

And thanks for the quick fix. You :rocket: !

**Comment by rkaminsk** [comment]
Btw. I recently automated the whole packaging process using github's actions. If you like, I can set this up for clorm, too. It would look a little like this:

  https://github.com/potassco/python-clingox/actions

Like this we would also get a pip and ubuntu package for clom.

**Comment by daveraja** [comment]
Creating these github actions would be great. Are these actions run only when a release is created?

**Comment by rkaminsk** [comment]
> Creating these github actions would be great. Are they run only when a release is created? In which case should I create the release now or wait till the action is created first?
> 
> Update: I'm just reading up a little on the workflows. I see that that they can be triggered manually so I will go ahead and create the release.

I am triggering them manually whenever needed. I have all the scripts ready to generate them. I can open a PR if you like. I will have to add repository secrets, so it will be important to only give access to people to the repository we fully trust. It would be best to add the actions before the release so that we can use them easily to deploy the release package too.

**Comment by daveraja** [comment]
> 
> I am triggering them manually whenever needed. I have all the scripts ready to generate them. I can open a PR if you like. I will have to add repository secrets, so it will be important to only give access to people to the repository we fully trust. It would be best to add the actions before the release so that we can use them easily to deploy the release package too.

Aagh!. Sorry I had already created the release before seeing your reply. But I can create a 1.2.1 release.

I'm happy to go with what you think is best regarding giving access due to repo secrets.

**Comment by rkaminsk** [comment]
> Aagh!. Sorry I had already created the release before seeing your reply. Feel free to open a PR and I will create a 1.2.1 release after merging.

No worries, we can make it work like this, too.
