### ISSUE TITLE
Querying in Clorm

### ISSUE THREAD

**Issue by Nsharma213** [potassco/clorm#61]
Hello Sir,
I am working on my thesis and I need a little help from you.
I am developing a model for market prices and extracting the data dynamically into clorm classes. In future if I want to have some specific thing printed I do not intend to change the main code but only the ASP code. Is it possible as the classes have specific configuration.

**Comment by daveraja** [comment]
From what you've described this doesn't sound like a use-case that clorm currently covers. I have a long running issue #34 to come up with catch-all fact format, but haven't progressed it any further.

If you can provide a more concrete example of what you're doing I can maybe suggest some options.

**Comment by Nsharma213** [comment]
Thankyou for your response.
I have created some classes for eg. like these

class Indexname(Predicate):
    name=StringField

class Indexvalue(Predicate):
    indexvalue=IntegerField

class Value(Predicate):
    date=DateField
    name=StringField
    indexvalue=IntegerField
    grid=ConstantField

class Reference(Predicate):
    name=StringField
    refname=StringField

class Suspect(Predicate):
    date=DateField
    indexvalue=IntegerField
    grid=ConstantField

These classes( Value, reference and others) help me extract the dynamic data from couchDB which I use in my FactBase for my ASP code. The Suspect right now I am not using. But my ASP code gives me a suspect using the following rules.
valreldiff(D,S,G):- value(D,N,V,G), value(D,N1,V1,G), S=((V-V1)*1000)/V1,reference(N,N1).
suspectv("validation check",D,S,G):- valreldiff(D,S,G),|S|>=relthreshold.
suspect("validation check: true",O):-O = #count{ G,S: suspectv(_,D,S,G)}>1.

My question is if I use the clorm queries to print the result, everytime I want a different type or probably a new result I will have to probably add new class or change the query, which I am not planning to. I would only like to change my ASP code for incorporating any changes. Right now I have used the #show thing to do it. I wanted to ask if this is the right approach or I should I use Clingo API  or any other solution you have

**Comment by daveraja** [comment]
I think it depends on what you want to do with the ASP output. 

If all you want to do is print out a string representation of a fact or add it to a table, then you could define a single output predicate and _reify_ the facts that you want to output. Basically something like the following:

In your ASP program:

     output(fact_that_may_change(X1,...,XN)) :- fact_that_may_change(X1,..,XN).
     #show output/1.

In your python code:

     class Output(Predicate):
           result=RawField

    .... calling clingo control to return a factbase...

    for fact in fb.query(Output).select(Output.result).all():
         print(f"Here is the fact {fact}")

**Comment by daveraja** [comment]
No further discussion so closing this issue

**Comment by Nsharma213** [comment]
I am sorry Sir, for not catching up. I am  I am a little confused as to what could be fb.query here?
I mean I would write the query to get the output result. but what is fb?

**Comment by daveraja** [comment]
`fb` in the above code snippet is a `FactBase` object that contains the facts. The solver generates models and from this you extract the facts into a clorm fact base, so that you can query it. Have a look at the quickstart guide: https://clorm.readthedocs.io/en/latest/clorm/quickstart.html and the corresponding example code: https://github.com/potassco/clorm/blob/master/examples/quickstart/quickstart.py

From your description above you don't need any sophisticated querying. So I think the easiest solution would be to not use clorm queries and instead to simply use clingo's `#show` syntax to output the facts that you want.

**Comment by Nsharma213** [comment]
Thankyou Sir, It worked with reification and the query too.
Thanks for your help
