### ISSUE TITLE
Performance of parse_fact_string() and parse_fact_files()

### ISSUE THREAD

**Issue by daveraja** [potassco/clorm#72]
The parsing is too slow. This becomes very noticeable on large (1+MB) files.

**Comment by florianfischer91** [comment]
Would it be possible instead of always using the ProgramBuilder that we just use the ProgramBuilder if `raise_nonfact=True` and else we add the aspstr directly. Something like
```python
if raise_nonfact:
    try:
        with clast.ProgramBuilder(ctrl) as bld:
            nfv = NonFactVisitor()
            def on_rule(ast: AST):
                nonlocal nfv, bld
                if nfv: nfv(ast)
                bld.add(ast)

        clast.parse_string(aspstr, on_rule)
    except ClingoParserWrapperError as e:
        raise e.exc
else:
    ctrl.add("base",[],aspstr)
```
I think this should also be faster because we don't have to use the callbacks (at least for `raise_nonfact=False`)?

**Comment by daveraja** [comment]
Yes you're right. That does avoid any callbacks. I've made the change and you can test it out using the pip dev version:

         pip install -i https://test.pypi.org/simple/ clorm

Note: you may need  to `pip uninstall clorm` first.

It does provide some speedup. Although now the real bottleneck is the unification process.

**Comment by florianfischer91** [comment]
Thanks for your quick response. I just tried and now it just takes half the time as before to create a factbase from a string :-)
Regarding the unification process: Atm i don't know how we could speed it up. Perhaps handle all facts with same name+arity in a separate process. But this would also bring some overhead...

**Comment by daveraja** [comment]
Great to see there is some improvement!. 

I am also a bit unsure how to speed up the unification process. Trying to do it in a separate processes would probably be something to try at the application level and not within the library (although maybe with some library support functions). 

I think there are some small things that I'm going to try to improve the tweak the implementation of the unification process, to make some small improvements. But, I don't think they will have a big improvement.

Another option could be to change the API to use a factory function. One issue with the current approach is that the Predicate initializer has to support multiple ways of creating fact objects, and the initializer has to test for these different mechanism. This adds some overhead. Having a more targeted factory function could possibly remove that overhead.

The final thought would be to try to off-load some of this processing to a C-extension. But this is adds a layer complexity to the project and I don't have hands-on experience with CFFI. But it is something I'd like to experiment with... sometime.

**Comment by daveraja** [comment]
Closing this issue and opened one that is more specific #82
