### ISSUE TITLE
Clorm fails to deploy on ubuntu bionic

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clorm#73]
The latest development version of clorm no longer deploys on Ubuntu Bionic. See <https://github.com/potassco/clorm/runs/4917830873?check_suite_focus=true#step:5:1730>. We could drop support. But it looks like it might be enough to install the typing-extensions module?

**Comment by daveraja** [comment]
Yes. Sorry, that you're getting spammed.

I did install the typing extensions modules. It works for python 3.7 and 3.8, but it doesn't have everything for Python 3.6. But @florianfischer91 pointed me to some ways around it, so I'm looking into it.

Ideally, I would like to have clorm distributed for everywhere that clingo is being officially supported so will try to get it working. Will also add 3.6 to the CI so can get things working in a branch without spamming others with deployment failures.

**Comment by rkaminsk** [comment]
> Yes. Sorry, that you're getting spammed.
> 
> I did install the typing extensions modules. It works for python 3.7 and 3.8, but it doesn't have everything for Python 3.6. But @florianfischer91 pointed me to some ways around it, so I'm looking into it.
> 
> Ideally, I would like to have clorm distributed for everywhere that clingo is being officially supported so will try to get it working. Will also add 3.6 to the CI so can get things working in a branch without spamming others with deployment failures.

It's your call. Python 3.6 is end of life. My gual is to support clingo for all maintained Python versions or longer if it is no major headache. I also like to use Ubuntu as a guideline because it is widely used. Supporting the full 10 years is a bit much, 5 years might (sometimes) be doable, the 2 years are important so that people can always use the latest LTS version. :smile:

**Comment by daveraja** [comment]
FYI @florianfischer91 I'm going to drop building the bionic (ubuntu 18.04) package. Bionic is not distributed with python3-typing-extensions so it would be a bit of a hassle to support. But clorm is now tested and working with python 3.6, so people using ubuntu 18.04 can just pip install from pypi. 

Regarding python 3.6. I'll keep testing with it while it is easy. But the next time we make some major changes that need features that are a hassle to work with python 3.6 we can drop it.
