### ISSUE TITLE
Support for aggregates

### ISSUE THREAD

**Issue by domoritz** [potassco/clorm#77]
I probably missed it in the docs but does clorm support aggregates like `2 {a; b; c; d} 3.`?

**Comment by daveraja** [comment]
Can you provide an example of how you would want to use this? 

Clorm is only about mapping the raw `clingo.Symbol` objects to a more user friendly Python object.  So it has nothing to do with the reasoning side of ASP. Where as aggregates are all about reasoning, so unless I'm missing something I don't see the connection.

**Comment by domoritz** [comment]
Ahh, that clarifies things for me. The problem domain would still be specified in ASP but the problem instances can be modeled with Python.
